plugins {
    id 'com.android.application'
}

android {
    namespace 'com.erp.carmusic'
    compileSdk 34

    defaultConfig {
        applicationId 'com.erp.carmusic'
        minSdk 28
        targetSdk 28
        versionCode 1
        versionName "0.1.0"
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.media:media:1.7.0'
    implementation 'androidx.media3:media3-exoplayer:1.3.1'
}
